version: '2.2'

services:
    ctf:
        build: ./
        volumes: 
            - ./xinetd:/etc/xinetd.d/xinetd:ro
        ports:
            - "1206:8888"
        expose:
            - "8888"
        pids_limit: 1024
        cpus: 0.5
        restart: unless-stopped
        
